# Generated by Django 5.1.1 on 2024-12-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_department_staff_departments_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
    ]
