# Generated by Django 5.1.1 on 2024-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_department_service_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slots',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='BookingSlot',
        ),
    ]
