# Generated by Django 5.1.1 on 2024-12-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_slots_delete_bookingslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slots',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='service.service')),
            ],
        ),
    ]
