# Generated by Django 5.1.1 on 2024-12-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(max_length=8),
        ),
    ]
