# Generated by Django 5.1.1 on 2024-12-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_is_otp_verified_account_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
