# Generated by Django 5.1.1 on 2024-12-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_account_otp_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
