# Generated by Django 5.1.1 on 2024-12-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_account_otp_generated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
