# Generated by Django 5.1.1 on 2024-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_car_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service_date',
            field=models.DateField(null=True),
        ),
    ]
